[toolchain]
package_manager = "yarn"
anchor_version = "0.30.1"



[features]
resolution = true
skip-lint = false

[programs.localnet]
ascii = "56cKjpFg9QjDsRCPrHnj1efqZaw2cvfodNhz4ramoXxt"

[programs.devnet]
ascii = "56cKjpFg9QjDsRCPrHnj1efqZaw2cvfodNhz4ramoXxt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
